# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jmoussu <jmoussu@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/08 12:11:22 by jmoussu           #+#    #+#              #
#    Updated: 2018/11/08 16:56:33 by jmoussu          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

EXEC = ft_display_file

SRC = *.c

all:
	gcc $(SRC) -o $(EXEC)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(EXEC)

re: fclean all
